export const STATE = [
  'ABIA', 'ADAMAWA', 'AKWA_IBOM', 'ANAMBRA', 'BAUCHI', 'BAYELSA', 'BENUE', 'BORNO',
  'CROSS_RIVER', 'DELTA', 'EBONYI', 'EDO', 'EKITI', 'ENUGU', 'GOMBE', 'IMO',
  'JIGAWA', 'KADUNA', 'KANO', 'KATSINA', 'KEBBI', 'KOGI', 'KWARA', 'LAGOS',
  'NASARAWA', 'NIGER', 'OGUN', 'ONDO', 'OSUN', 'OYO', 'PLATEAU', 'RIVERS',
  'SOKOTO', 'TARABA', 'YOBE', 'ZAMFARA', 'FCT', 'NATIONAL',
];

export const CATEGORY = [
  'PRESIDENTIAL', 'GUBERNATORIAL', 'SENATORIAL',
  'STATE_REPRESENTATIVE', 'STATE_ASSEMBLY', 'LOCAL_COUNSELOR',
];

export const CITIZENSHIP_TYPE = [
  'NATURALIZATION', 'REGISTRATION', 'DUAL_CITIZENSHIP', 'HONORARY',
];

export const PERMISSION = [
  'CAN_VOTE', 'CAN_UPLOAD_FILE', 'CAN_APPROVE_VOTER',
  'CAN_VIEW_METRICS', 'CAN_VIEW_ELECTORATE', 'CAN_VIEW_VOTE',
  'CAN_UPDATE_ELECTORATE',
];
